let theme='light';try{theme=localStorage.getItem('haru-theme')||'light'}catch(e){};document.documentElement.dataset.theme=theme;const themeStyle=document.createElement('style');themeStyle.textContent=':root{--bg:#fff;--ink:#000;--surface:#f3f3f3;--border:#d5d5d5}:root[data-theme="dark"]{--bg:#000;--ink:#fff;--surface:#181818;--border:#444}body,#app,nav{background:var(--bg);color:var(--ink)}.theme-toggle{border:1px solid var(--border);border-radius:9px;padding:8px 11px;min-height:42px}.attendance{border:1px solid var(--border);border-radius:12px;padding:18px;margin:22px 0}.attendance-total{font-size:24px}.streak{font-size:20px}.attendance-rate{font-size:28px}.attendance-progress{width:100%;height:8px;accent-color:var(--ink)}';document.head.appendChild(themeStyle);function toggleTheme(){theme=theme==='dark'?'light':'dark';document.documentElement.dataset.theme=theme;try{localStorage.setItem('haru-theme',theme)}catch(e){}render()}
const lessons=[
{title:'카페에서 주문하기',tag:'여행',goal:'원하는 음료를 정중하게 주문해요.',pattern:"I’d like …, please.",ko:'…을 주세요.',target:"I'd like a coffee, please.",meaning:'커피 한 잔 주세요.',tip:'I want보다 I’d like를 쓰면 더 정중한 요청이 돼요.',words:['coffee','tea','water'],dialogue:[["Hi! What can I get for you?",'안녕하세요! 무엇을 드릴까요?'],["I'd like a coffee, please.",'커피 한 잔 주세요.'],['Hot or iced?','따뜻한 걸로 드릴까요, 아이스로 드릴까요?'],['Iced, please.','아이스로 주세요.']],prompts:[['What can I get for you?','커피 한 잔을 주문하세요.',"I'd like a coffee, please."],['Hot or iced?','아이스로 요청하세요.','Iced, please.'],['Anything else?','더 필요한 것은 없다고 답하세요.',"No, thank you."]]},
{title:'호텔에서 요청하기',tag:'여행',goal:'늦은 체크아웃을 요청해요.',pattern:"I’d like …, please.",ko:'…을 부탁드려요.',target:"I'd like a late checkout, please.",meaning:'늦은 체크아웃을 부탁드려요.',tip:'late checkout은 정해진 시간보다 늦게 퇴실하는 것이에요.',words:['a late checkout','an extra towel','a quiet room'],dialogue:[['How can I help you?','무엇을 도와드릴까요?'],["I'd like a late checkout, please.",'늦은 체크아웃을 부탁드려요.'],['What time would you like to check out?','몇 시에 체크아웃하고 싶으세요?'],['At two, if possible.','가능하면 2시에요.']],prompts:[['How can I help you?','늦은 체크아웃을 요청하세요.',"I'd like a late checkout, please."],['What time would you like to check out?','가능하면 2시라고 말하세요.','At two, if possible.'],['Two is fine.','감사 인사를 하세요.','Thank you for your help.']]},
{title:'업무 미팅 요청하기',tag:'비즈니스',goal:'짧은 미팅을 요청하고 시간을 정해요.',pattern:"I’d like to …",ko:'…하고 싶습니다.',target:"I'd like to schedule a meeting.",meaning:'미팅 일정을 잡고 싶습니다.',tip:'행동을 말할 때는 I’d like 뒤에 to와 동사를 붙여요.',words:['schedule a meeting','discuss the plan','ask a question'],dialogue:[['Do you have a moment?','잠깐 시간 있으세요?'],["Sure. What do you need?",'그럼요. 무슨 일이세요?'],["I'd like to schedule a meeting.",'미팅 일정을 잡고 싶습니다.'],['How about tomorrow at ten?','내일 10시는 어떠세요?']],prompts:[['What can I help you with?','미팅을 잡고 싶다고 말하세요.',"I'd like to schedule a meeting."],['When are you available?','내일 10시를 제안하세요.','How about tomorrow at ten?'],['That works for me.','그때 만나자고 말하세요.','Great. See you then.']]},
{title:'시간 변경 요청하기',tag:'비즈니스',goal:'다른 시간을 정중하게 제안해요.',pattern:'Could we …?',ko:'우리 …할 수 있을까요?',target:'Could we meet at three instead?',meaning:'대신 3시에 만날 수 있을까요?',tip:'instead는 ‘대신에’라는 뜻이에요. 바꾸고 싶은 시간을 앞에 말해요.',words:['meet at three instead','meet tomorrow instead','start at ten instead'],dialogue:[['Are we still meeting at two?','우리 여전히 2시에 만나는 거죠?'],['Could we meet at three instead?','대신 3시에 만날 수 있을까요?'],['Sure. Three works for me.','네. 저는 3시 괜찮아요.'],['Thank you. See you then.','감사합니다. 그때 뵐게요.']],prompts:[['Are we still meeting at two?','대신 3시를 제안하세요.','Could we meet at three instead?'],['Would tomorrow be better?','내일도 괜찮다고 답하세요.','Tomorrow works for me.'],["Let's meet tomorrow at three.",'시간을 확인하며 마무리하세요.','Great. See you tomorrow at three.']]},
{title:'여행과 업무에서 말해보기',tag:'역할극',goal:'힌트를 줄이고 배운 표현을 꺼내 써요.',pattern:"I’d like … / Could we …?",ko:'요청과 제안 표현 복습',target:"I'd like to schedule a meeting.",meaning:'미팅 일정을 잡고 싶습니다.',tip:'먼저 혼자 말해본 뒤 예문을 확인하세요. 같은 뜻의 다른 표현도 괜찮아요.',words:['a coffee, please','a late checkout, please','to schedule a meeting'],dialogue:[['What would you like?','무엇을 원하세요?'],["I'd like a tea, please.",'차 한 잔 주세요.'],['When shall we meet?','언제 만날까요?'],['Could we meet at three?','3시에 만날 수 있을까요?']],prompts:[['What would you like?','차 한 잔을 주문하세요.',"I'd like a tea, please."],['How can I help you?','늦은 체크아웃을 요청하세요.',"I'd like a late checkout, please."],['When shall we meet?','3시를 제안하세요.','Could we meet at three?']]},
{title:'어려웠던 표현 다시 말하기',tag:'복습',goal:'이번 주 표현을 다시 말하며 익숙해져요.',pattern:"I’d like …, please.",ko:'배운 표현을 다시 꺼내보기',target:"I'd like a late checkout, please.",meaning:'늦은 체크아웃을 부탁드려요.',tip:'정답을 바로 보기보다 5초만 먼저 떠올려보세요.',words:['a coffee','a late checkout','an extra towel'],dialogue:[['What can I get for you?','무엇을 드릴까요?'],["I'd like a coffee, please.",'커피 한 잔 주세요.'],['Anything else?','더 필요하신가요?'],['No, thank you.','아니요, 감사합니다.']],prompts:[['What can I get for you?','커피를 주문하세요.',"I'd like a coffee, please."],['How can I help you?','늦은 체크아웃을 요청하세요.',"I'd like a late checkout, please."],['When are you free?','내일 10시를 제안하세요.','How about tomorrow at ten?']]},
{title:'새로운 상황에 써보기',tag:'주간 확인',goal:'배운 표현으로 새로운 요청을 해봐요.',pattern:"I’d like … / Could we …?",ko:'새로운 상황에 응용하기',target:"I'd like some water, please.",meaning:'물 좀 주세요.',tip:'물은 셀 수 없는 명사라 some water라고 해요.',words:['some water, please','an extra towel, please','to ask a question'],dialogue:[['Can I help you?','도와드릴까요?'],["I'd like some water, please.",'물 좀 주세요.'],['Of course. Here you are.','물론이죠. 여기 있습니다.'],['Thank you.','감사합니다.']],prompts:[['Can I help you?','물을 요청하세요.',"I'd like some water, please."],['Do you need anything for your room?','수건을 하나 더 요청하세요.',"I'd like an extra towel, please."],['Shall we start at nine?','대신 10시에 시작하자고 제안하세요.','Could we start at ten instead?']]}];
const roadmap=['요청하기','자기소개','질문과 확인','일정 조율','선호와 이유','문제와 도움 요청','제안과 반응','비교와 선택','경험과 진행 상황','반대 의견과 대안','후속 질문 대응','종합 역할극'];
let saved;try{saved=JSON.parse(localStorage.getItem('haru-v1'))}catch{}let data=saved&&Array.isArray(saved.sessions)&&Array.isArray(saved.cards)?saved:{sessions:[],cards:[]};
let page='today',lesson=0,step=0,short=false,turn=0,hint=0,showKo=true,slow=true,feedback='',answer='',recognizer=null,recording=false,started=0;
const $=s=>document.querySelector(s), esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function save(){try{localStorage.setItem('haru-v1',JSON.stringify(data))}catch{notify('이 기기에서 저장이 제한돼 기록이 유지되지 않을 수 있어요.')}}
function notify(t){$('#notice').textContent=t;$('#notice').style.display='block';setTimeout(()=>$('#notice').style.display='none',3500)}
function stop(){if(window.speechSynthesis)window.speechSynthesis.cancel();if(recognizer){recognizer.abort();recognizer=null}recording=false}
function speak(text){if(!window.speechSynthesis){notify('이 브라우저는 음성 재생을 지원하지 않아요. 문장을 소리 내어 읽어주세요.');return}window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='en-US';u.rate=slow?.78:1;const v=speechSynthesis.getVoices().find(v=>v.lang==='en-US');if(v)u.voice=v;u.onerror=e=>{if(e.error!=='interrupted'&&e.error!=='canceled')notify('음성을 재생하지 못했어요. 다시 눌러주세요.')};speechSynthesis.speak(u)}
const icons=['<path d="M3 10 12 3l9 7v11h-6v-7H9v7H3z"/>','<path d="M4 5h7v16H4zM13 5h7v16h-7z"/>','<path d="M5 20V12M12 20V4M19 20V8"/>'];
function shell(body,nav=true){$('#app').innerHTML=`<header><span class="brand">하루 한마디<span style="color:#24594e">.</span></span><div class="header-actions"><span class="muted header-subtitle">나의 영어회화</span><button class="theme-toggle" data-action="theme" aria-label="${theme==='dark'?'라이트모드로 전환':'다크모드로 전환'}">${theme==='dark'?'라이트모드':'다크모드'}</button></div></header>${body}${nav?`<nav aria-label="주 메뉴">${['오늘','복습','내 기록'].map((t,i)=>`<button data-page="${['today','review','record'][i]}" class="${page===['today','review','record'][i]?'on':''}" ${page===['today','review','record'][i]?'aria-current="page"':''}><svg viewBox="0 0 24 24" aria-hidden="true">${icons[i]}</svg>${t}</button>`).join('')}</nav>`:''}`;}
function localDay(d=new Date()){return `${d.getFullYear()}-${d.getMonth()+1}-${d.getDate()}`}
function weekSessions(){let d=new Date();d.setHours(0,0,0,0);d.setDate(d.getDate()-((d.getDay()+6)%7));return data.sessions.filter(s=>s.at>=d.getTime())}
function render(){if(page==='learn')return renderLesson();if(page==='complete')return completeView();if(page==='review')return review();if(page==='record')return record();today()}
function today(){let next=lessons.findIndex((l,i)=>!data.sessions.some(s=>s.lesson===i));if(next<0)next=0;lesson=next;const l=lessons[next],count=new Set(weekSessions().map(s=>localDay(new Date(s.at)))).size;shell(`<section class="hero"><div class="eyebrow">WEEK 01 · 정중하게 요청하기</div><h1>오늘도, 한마디씩.</h1><p class="lead">짧게 듣고, 직접 말해보세요.</p><div style="margin-top:25px"><span class="pill">${l.tag} · DAY ${next+1}</span><h2 style="margin:12px 0 4px">${l.title}</h2><p class="lead">${l.goal}</p></div><button class="primary" data-start="${next}">10분 학습 시작</button><button class="small" data-quick="${next}">바쁜 날엔 3분만 학습</button></section><section class="section"><div class="sectionhead"><h2>이번 주의 작은 습관</h2><span class="muted">${count} / 5일</span></div><div class="days">${['월','화','수','목','금','토','일'].map((d,i)=>{let dt=new Date();dt.setDate(dt.getDate()-((dt.getDay()+6)%7)+i);let done=weekSessions().some(s=>localDay(new Date(s.at))===localDay(dt));return `<div class="day">${d}<div class="circle ${done?'done':''}">${done?'✓':'·'}</div></div>`}).join('')}</div></section><section class="section"><h2>이번 주 수업</h2>${lessons.map((l,i)=>`<button class="row ${i===next?'active':''}" data-start="${i}"><span class="num">${String(i+1).padStart(2,'0')}</span><div><div class="title">${l.title}</div><div class="sub">${l.tag} · ${data.sessions.some(s=>s.lesson===i)?'학습 완료 · 다시 연습':'10분'}</div></div><span class="arrow">›</span></button>`).join('')}</section><section class="section"><h2>이번 주 핵심 표현</h2><div class="quote">I’d like …, please.<span>원하는 것을 정중하게 요청할 때</span></div></section>`)}
function start(i,q=false){stop();lesson=i;short=q;step=0;turn=0;hint=0;answer='';feedback='';page='learn';started=Date.now();render();window.scrollTo(0,0)}
function controls(){return `<div class="tools"><button data-action="listen">▷ 듣기</button><button data-action="speed">${slow?'느리게 · 0.8×':'보통 · 1×'}</button><button data-action="translation">${showKo?'해석 숨기기':'해석 보기'}</button></div>`}
function renderLesson(){const l=lessons[lesson],stages=short?['떠올리기','핵심 표현','말해보기']:['떠올리기','대화 듣기','핵심 표현','역할극','마무리'];let kind=short?[0,2,3][step]:step;let content='';if(kind===0)content=`<h1>먼저 떠올려볼까요?</h1><p class="lead">${lesson===0?'오늘 쓸 표현을 가볍게 떠올려보세요.':'지난 표현을 소리 내어 말해보세요.'}</p><div class="note">커피 한 잔 주세요.</div><button class="secondary" data-action="reveal">예문 확인하기</button><div id="reveal" hidden><p class="english">I'd like a coffee, please.</p><button class="textbtn" data-say="I'd like a coffee, please.">▷ 예문 듣기</button></div>`;
if(kind===1)content=`<h1>${l.title}</h1><p class="lead">먼저 듣고, 내 문장을 따라 말해보세요.</p>${controls()}<div class="dialogue">${l.dialogue.map((d,i)=>`<div class="line ${i%2?'you':''}"><span class="muted">${i%2?'나':'상대'}</span><p class="english">${esc(d[0])}</p>${showKo?`<p class="translation">${d[1]}</p>`:''}</div>`).join('')}</div>`;
if(kind===2)content=`<h1>이 표현 하나면 돼요.</h1><p class="english">${esc(l.pattern)}</p><p class="translation">${l.ko}</p><div class="note">${l.tip}</div><p class="english">${esc(l.target)}</p>${showKo?`<p class="translation">${l.meaning}</p>`:''}${controls()}<h2>단어를 바꿔 3번 말해보세요.</h2>${l.words.map(w=>`<div class="row"><span>${esc(w)}</span></div>`).join('')}<button class="textbtn" data-action="bookmark">복습할 표현에 담기</button>`;
if(kind===3){const p=l.prompts[turn];content=`<span class="pill">${turn+1} / ${short?1:l.prompts.length}번 대화</span><h1>내 차례예요.</h1><p class="english">${esc(p[0])}</p><button class="textbtn" data-say="${esc(p[0])}">▷ 상대 말 듣기</button><div class="note">${p[1]}</div><button class="secondary" data-action="mic" id="mic">${recording?'듣는 중 · 멈추기':'마이크로 답하기'}</button><p class="muted">음성 인식이 안 되면 아래에 직접 입력하거나, 소리 내어 연습한 뒤 예문을 확인하세요.</p><textarea class="answer" id="answer" placeholder="내가 말한 영어" aria-label="나의 영어 답변">${esc(answer)}</textarea><button class="textbtn" data-action="hint">${hint?'예문 보기':'힌트 보기'}</button>${hint?`<div class="note">${hint===1?esc(p[2].split(' ').slice(0,2).join(' '))+' …':esc(p[2])}</div>`:''}<button class="secondary" data-action="check">예문과 비교하기</button>${feedback?`<div class="feedback" role="status">${feedback}</div>`:''}`;}
if(kind===4)content=`<h1>마지막으로, 혼자 말해요.</h1><div class="note">${l.meaning}</div><p class="lead">해석만 보고 말한 뒤 예문과 비교하세요.</p><button class="secondary" data-action="reveal">예문 확인하기</button><div id="reveal" hidden><p class="english">${esc(l.target)}</p><button class="textbtn" data-say="${esc(l.target)}">▷ 듣기</button></div><button class="textbtn" data-action="bookmark">내일 한 번 더 복습하기</button>`;
shell(`<button class="back" data-action="exit">‹ 오늘로 돌아가기</button><div class="sectionhead"><span class="muted">${short?'3분':'10분'} 학습 · ${stages[step]}</span><span class="muted">${step+1} / ${stages.length}</span></div><div class="progress"><i style="width:${(step+1)/stages.length*100}%"></i></div>${content}<div class="bottom"><button class="primary" data-action="next">${step===stages.length-1&&(kind!==3||short||turn===2)?'학습 마치기':kind===3&&turn<2&&!short?'다음 대화':'다음'}</button>${step>0?'<button class="small" style="width:100%" data-action="prev">이전 단계</button>':''}</div>`,false)}
function bookmark(){const l=lessons[lesson];if(!data.cards.some(c=>c.text===l.target))data.cards.push({text:l.target,ko:l.meaning,due:Date.now(),level:0});save();notify('복습할 표현에 담았어요.')}
function finish(){stop();data.sessions.push({lesson,short,at:Date.now(),seconds:Math.max(1,Math.round((Date.now()-started)/1000))});const l=lessons[lesson];if(!data.cards.some(c=>c.text===l.target))data.cards.push({text:l.target,ko:l.meaning,due:Date.now()+86400000,level:0});save();page='complete';render()}
function completeView(){shell(`<div class="center"><div class="check">✓</div><span class="eyebrow">DAY ${lesson+1} 완료</span><h1>오늘의 한마디를 쌓았어요.</h1><p class="lead">${lessons[lesson].goal}</p></div><div class="quote">${esc(lessons[lesson].target)}<span>${lessons[lesson].meaning}</span></div><p class="note">오늘 표현은 내일 복습에 나타나요. 짧게라도 다시 말해보세요.</p><button class="primary" data-page="today">오늘 화면으로</button>`)}
function review(){const due=data.cards.filter(c=>c.due<=Date.now());shell(`<div class="eyebrow">REVIEW</div><h1>다시 말하면, 내 표현.</h1><p class="lead">오늘 복습할 표현 ${due.length}개 · 전체 ${data.cards.length}개</p>${data.cards.length?data.cards.map((c,i)=>`<section class="section"><span class="pill">${c.due<=Date.now()?'오늘 복습':new Date(c.due).toLocaleDateString('ko-KR',{month:'short',day:'numeric'})+' 복습'}</span><p>${esc(c.ko)}</p><details><summary>영어 표현 확인</summary><p class="english">${esc(c.text)}</p><button class="textbtn" data-say="${esc(c.text)}">▷ 듣기</button></details><div class="tools"><button data-again="${i}">아직 어려워요</button><button data-know="${i}">혼자 말했어요</button></div></section>`).join(''):`<div class="note">수업을 마치면 표현이 자동으로 담겨요. 학습 중에도 복습할 표현을 저장할 수 있어요.</div><button class="primary" data-start="0">첫 수업 시작하기</button>`}`)}
function record(){const days=new Set(data.sessions.map(s=>localDay(new Date(s.at)))).size;const n=new Set(data.sessions.map(s=>s.lesson)).size;shell(`<div class="eyebrow">MY LEARNING</div><h1>조금씩, 익숙해지는 중.</h1><div class="grid"><div><div class="metric">${days}</div><span class="lead">학습한 날</span></div><div><div class="metric">${n}<span style="font-size:20px;color:#8b9791"> / 7</span></div><span class="lead">완료한 수업</span></div></div><h2>내가 연습한 상황</h2>${n?lessons.filter((l,i)=>data.sessions.some(s=>s.lesson===i)).map(l=>`<div class="row"><span style="color:#24594e">✓</span><span>${l.title}</span></div>`).join(''):'<p class="note">첫 수업을 마치면 여기에 기록돼요.</p>'}<section class="section"><h2>12주 학습 방향</h2><p class="muted">현재는 1주차 수업을 학습할 수 있어요. 2~12주차는 앞으로의 교육 계획입니다.</p>${roadmap.map((r,i)=>`<div class="row"><span class="num">${i+1}주</span><span>${r}</span>${i===0?'<span class="pill" style="margin-left:auto">학습 가능</span>':''}</div>`).join('')}</section><section class="section"><details><summary>학습 방식과 EBS 참고 자료</summary><p class="lead">짧은 패턴 연습, 생활 대화, 직접 말하기 방식은 EBS 영어교육 구성을 참고했어요. 이 앱의 대화문은 직접 만든 콘텐츠이며 EBS 공식 앱은 아닙니다.</p><p><a href="https://www.ebse.co.kr/apps/main/main.do" target="_blank" rel="noopener">EBS English 보기 ↗</a></p><p><a href="https://home.ebs.co.kr/speakinge/" target="_blank" rel="noopener">입이 트이는 영어 보기 ↗</a></p></details><details><summary>기록과 음성 사용 안내</summary><p class="lead">학습 기록은 이 기기의 브라우저에 저장돼요. 다른 기기와 자동으로 연결되지 않으며 브라우저 데이터를 지우면 기록도 삭제돼요.</p><p class="lead">듣기와 음성 인식은 브라우저 지원 여부에 따라 달라져요. 음성 인식 시 브라우저 제공 서비스로 음성이 전송될 수 있어요. 앱은 음성 녹음을 보관하지 않아요. 답변 비교는 예문과 단어를 비교하는 연습 도구이며 AI 의미·발음 평가가 아닙니다.</p></details><details><summary>홈 화면에 추가하기</summary><p class="lead">아이폰: Safari의 공유 메뉴에서 ‘홈 화면에 추가’를 선택하세요. 안드로이드: Chrome 메뉴에서 ‘홈 화면에 추가’를 선택하세요.</p></details></section>`)}
function mic(){const R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R){notify('이 브라우저에서는 직접 입력으로 연습해주세요.');$('#answer').focus();return}if(recording){recognizer?.stop();return}recognizer=new R();recognizer.lang='en-US';recognizer.interimResults=false;recognizer.onstart=()=>{recording=true;if($('#mic'))$('#mic').textContent='듣는 중 · 멈추기'};recognizer.onresult=e=>{answer=e.results[0][0].transcript;if($('#answer'))$('#answer').value=answer};recognizer.onerror=e=>notify(e.error==='not-allowed'?'마이크 권한을 허용하거나 직접 입력해주세요.':'잘 듣지 못했어요. 다시 말하거나 입력해주세요.');recognizer.onend=()=>{recording=false;if($('#mic'))$('#mic').textContent='마이크로 답하기'};try{recognizer.start()}catch{notify('음성 인식을 시작하지 못했어요. 직접 입력해주세요.')}}
document.addEventListener('input',e=>{if(e.target.id==='answer')answer=e.target.value});
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const d=b.dataset;if(d.page){stop();page=d.page;render();window.scrollTo(0,0);return}if(d.start!==undefined)return start(Number(d.start));if(d.quick!==undefined)return start(Number(d.quick),true);if(d.say)return speak(d.say);if(d.again!==undefined){const c=data.cards[Number(d.again)];c.due=Date.now()+86400000;c.level=0;save();review();notify('내일 다시 연습해요.');return}if(d.know!==undefined){const c=data.cards[Number(d.know)];c.due=Date.now()+[1,3,7,14][Math.min(c.level,3)]*86400000;c.level++;save();review();notify('다음 복습 일정을 정했어요.');return}const l=lessons[lesson];switch(d.action){case'exit':stop();page='today';render();break;case'reveal':$('#reveal').hidden=false;b.hidden=true;break;case'speed':slow=!slow;renderLesson();break;case'translation':showKo=!showKo;renderLesson();break;case'listen':speak(!short&&step===1?l.dialogue.map(d=>d[0]).join(' ... '):l.target);break;case'bookmark':bookmark();break;case'hint':hint=Math.min(2,hint+1);renderLesson();break;case'mic':mic();break;case'check':{if(!answer.trim()){notify('먼저 답변을 입력하거나 말해주세요.');return}const norm=s=>s.toLowerCase().replace(/[’]/g,"'").replace(/[^a-z0-9 ]/g,'').replace(/\s+/g,' ').trim();const target=l.prompts[turn][2],a=norm(answer),t=norm(target);feedback=a===t?'예문과 같은 표현을 말했어요. 한 번 더 소리 내어 말해보세요.':`예문은 “${esc(target)}”예요. 내 답과 비교해 다시 말해보세요. 다른 표현도 뜻이 통할 수 있어요.`;renderLesson();break}case'prev':stop();step=Math.max(0,step-1);turn=0;hint=0;feedback='';answer='';render();break;case'next':stop();if((short?step===2:step===3)&&!short&&turn<2){turn++;hint=0;feedback='';answer='';render()}else if(step===(short?2:4))finish();else{step++;render()}window.scrollTo(0,0);break}});
document.addEventListener('click',e=>{if(e.target.closest('[data-action="theme"]'))toggleTheme()});
const oldFinish=finish;finish=function(){oldFinish();const days=[...new Set(data.sessions.map(s=>localDay(new Date(s.at))))].sort();const total=days.length;let streak=total?1:0;for(let i=total-1;i>0&&new Date(days[i])-new Date(days[i-1])===86400000;i--)streak++;const box=document.createElement('div');box.className='attendance';box.innerHTML='<span class="eyebrow">출석 기록</span><p class="attendance-total">누적 <strong>'+total+'일차</strong></p><p class="streak">연속 '+streak+'일차</p><p class="muted">학습 완료한 날 기준으로 집계돼요.</p>';const app=document.querySelector('#app');app.insertBefore(box,app.firstChild)};
render();
